export const LABELS = {
  active: "active",
  disabled: "disabled",
  status: "status",
  changeTokenStatus: "change token status",
  hasPrivateAccess: "access to private methods",
  noPrivateAccess: "no access to private methods",
  owner: "owner",
  createdAt: "created at",
  activeBefore: "active before",
  comment: "comment",
  details: "details",
  copy: "copy to clipboard",
  copied: "copied to clipboard",
  tokenId: "token ID",
  createToken: "create token",
  backToTheForm: "back to the form",
  tokenList: "token list",
  logOut: "log out",
  enterKey: "enter api key",
  showKey: "show api key",
  hideKey: "hide api key",
  submit: "submit",
  error: "error",
  allTokensLoaded: "all tokens loaded",
  notFound: "404: not found",
  fullName: "full name",
  commentPlaceholder: "any additional info at your discretion",
  setPoints: "set balance points",
  setActiveBefore: "set active before",
  changeActiveBefore: "change token active before date",
  setHasPrivateAccess: "access to private methods",
  confirmHasPrivateAccess: "confirm access to private methods",
  confirmHasPrivateAccessPrompt1: "You have checked the option",
  confirmHasPrivateAccessPrompt2:
    "Confirm creating the token with such credentials or get back to the form.",
  reset: "reset",
  yes: "yes",
  no: "no",
  points: "points",
  selectDate: "select date",
  selectDateRange: "select date range",
  noRecordsFound: "no records found",
  tokenLogs: "token usage logs",
  time: "time",
  endpoint: "endpoint",
  price: "price",
  traceId: "trace id",
  logsPerPage: "logs per page",
  next: "next",
  toNextPage: "to the next page",
  prev: "prev",
  toPrevPage: "to the previous page",
  morePages: "more pages",
  cancel: "cancel",
  currentPoints: "current points",
  changePointsPrompt:
    "You can subtract or add points to the current account or edit the resulting value.",
  currentPointsZeroPrompt:
    "There are no points on the account. Do you want to make a deposit?",
  tokenCreated: "token successfully created",
  createMoreTokens: "create more tokens",
  toTheList: "go to the list",
  whatToDo: "you can create more tokens or go to the token list",
};

export const ERRORS = {
  wrongKey: "Wrong api key. Please try again",
  negativePoints: "Points can not be negative",
  pastDate: "The date should be in the future",
  serverError: "Server error",
  error: "Error",
  required: "Field is required",
  wrongDateFormat: "Wrong date format",
  nonNegativeInteger: "This should be a non negative integer",
  shortText: (min: number) =>
    `Too short text, minimal length should be ${min} letters`,
  oneOfFieldsRequired: (one: string, two: string) =>
    `One of the fields "${one}" or "${two}" should be filled`,
};
