/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TokenCreateRouteImport } from './../routes/token-create'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as AboutRouteImport } from './../routes/about'
import { Route as _404RouteImport } from './../routes/__404'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as TokensIdRouteImport } from './../routes/tokens.$id'

const TokenCreateRoute = TokenCreateRouteImport.update({
  id: '/token-create',
  path: '/token-create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const _404Route = _404RouteImport.update({
  id: '/__404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensIdRoute = TokensIdRouteImport.update({
  id: '/tokens/$id',
  path: '/tokens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/token-create': typeof TokenCreateRoute
  '/tokens/$id': typeof TokensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/token-create': typeof TokenCreateRoute
  '/tokens/$id': typeof TokensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__404': typeof _404Route
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/token-create': typeof TokenCreateRoute
  '/tokens/$id': typeof TokensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/login' | '/token-create' | '/tokens/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/token-create' | '/tokens/$id'
  id:
    | '__root__'
    | '/'
    | '/__404'
    | '/about'
    | '/login'
    | '/token-create'
    | '/tokens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _404Route: typeof _404Route
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  TokenCreateRoute: typeof TokenCreateRoute
  TokensIdRoute: typeof TokensIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/token-create': {
      id: '/token-create'
      path: '/token-create'
      fullPath: '/token-create'
      preLoaderRoute: typeof TokenCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__404': {
      id: '/__404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$id': {
      id: '/tokens/$id'
      path: '/tokens/$id'
      fullPath: '/tokens/$id'
      preLoaderRoute: typeof TokensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _404Route: _404Route,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  TokenCreateRoute: TokenCreateRoute,
  TokensIdRoute: TokensIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
